"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

PACKAGES = ['bs4', 'mechanicalsoup', 'PIL', 'psutil', 'requests', 'selenium', 'wheel']
MODULES = ['calculate_statistics.py', 'combobox_dicts.py', 'country_dicts.py', 'display_results.py', 'hostelworld.py',
           'myallocator.py', 'sa_options.py', 'statistic_amt.py']
APP = ['main.py']
DATA_FILES = ['.data_files', '.images', '.icons', '.phantomjs']
OPTIONS = {
    'argv_emulation': False,
    'iconfile': '.icons/statistik-rechner-black.icns',
    'packages': PACKAGES,
    'includes': MODULES
}

setup(
    app=APP,
    name="Statistik Rechner",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
